### ISSUE TITLE
code not work

### ISSUE THREAD

**Issue by vipCodeError** [diegodalbosco/TextHoler.js#1]
**HTML markup**

```
<span id="test">TEXT HOLER</span>
```

**jQuery**

```
$('#test').textHoler({
    background: "http://i.giphy.com/fnMmGzRnQD6Ny.gif"
});
```

code not work only show gif

**Comment by diegodalbosco** [comment]
I just tried and it's working, what browser are you using?

**Comment by vipCodeError** [comment]
this have not work in firefox and i try opera,chrome work smothly.

**Comment by diegodalbosco** [comment]
Yes, you're right, on Firefox it doesn't work.
